### ISSUE TITLE
java.lang.IllegalArgumentException: remaining() < size < needed

### ISSUE THREAD

**Issue by vanhelsing71** [ShoYamanishi/AndroidVUMeter#1]
Hi, occasionally I encounter the error:

```
java.lang.IllegalArgumentException: remaining() < size < needed 
https://github.com/ShoYamanishi/AndroidVUMeter
at android.opengl.GLES20.glBufferData(Native Method)
```

at row 186 of the Renderer:

https://github.com/ShoYamanishi/AndroidVUMeter/blob/c97d3c6fe6d6f08e766f2014cc8929e888baaa86/app/src/main/java/com/example/vumeter/VUMeterRenderer.java#L186

Can't figure out why, but currently I worked around the problem with a try catch:

```
//Sometimes we encounter an exception:
        // java.lang.IllegalArgumentException: remaining() < size < needed
        // at android.opengl.GLES20.glBufferData(Native Method)
        //Cant'understand the reason
        //We trap it and do nothing... seems fine
        try{
            GLES20.glBufferData(
                    GLES20.GL_ARRAY_BUFFER,
                    mModel.mVerticesByteSize(),
                    mModel.mVerticesNative,
                    GLES20.GL_STATIC_DRAW
            );
        } catch (IllegalArgumentException e){
            Log.w(TAG, "Catched an IllegalArgumentException");
        }
```

**Comment by ShoYamanishi** [comment]
Hi Vanhelsing71,
Thanks for reporting this. On what HW/SW does this occur?
Here's my initial quick analysis.
Probably it is due to a potential race condition around VUMeterModel::mVerticesNative, which is  accessed by VUMeterModel::onUpdateRMS() and by VUMeterRenderer::render(). The former is called by the audio rendering cycle, and the latter is called by the GL render cycle. Probably the easiest solution is to move VUMeterModel::makeHandVertices() into VUMeterRenderer::render().

**Comment by vanhelsing71** [comment]
hi @ShoYamanishi , I have the issue on Samsung Galaxy S9 with latest android update (Android 10), I will try the suggestion.

**Comment by vanhelsing71** [comment]
Modifying the code as per your suggestion is a little beyond my capabilities. For my needs the try/catch workaround is enough. Closing the issue.
